<!DOCTYPE html>
<html lang="hu-HU">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>Hajok
</head>
<body>
    <header>
     <h1>Vitorlázás tanítása 3. évfolyam</h1>

    </header>
    <main>

        <h3>Tematika</h3>
        <ol>
            <li>A vízi telep rendjének megtanítása.</li>
            <li>A hajók tárolásának megtanítása, betartása.</li>
            <li>Az eszközökre való igényesség megtanítása.</li>
            <li>Hajók precíz, biztonságos, önálló felszerelése.</li>
            <li>Alapvető haladási irányok megismerése:</li>
            </li>
        </v1>

        <ol>
        <li>élszél</li>
        <li>hátszél</li>
        <li>háromnegyed szél</li>
        <li>negyed szél</li>
        </ol>
        <ul>
            Manőverek megismerése:
        </ul>
        <ol>
        <li>élesedés</li>
        <li>leejtés</li>
        <li>fordulás</li>
        <li>perdülés</li>
        </ol>
        Jótanácsok
        
        <p>A tanítás első lépése mindig a szélirány meghatározásával történjen. Tanítsuk meg a gyerekeknek, milyen módon milyen eszközökkel lehet a szélirányt hozzávetőlegesen meghatározni.
        A haladási irányok előtt a szélbeállás helyzetét ismertessük meg velük először.</p>
        <p>Minden egyes iránynak a nevét, a hajó haladásának legfontosabb ismérveit mutassuk be nekik.</p>
        <p>A hajó haladási irányára és a szél viszonyára igyekezzünk mindig olyan kulcsszavakat használni (hátszél: hátulról fújja a hajót a szél), amely segíti a tanulást.</p>
        <p>A gyakorlati bemutatás a már említett tároló kocsin lévő felszerelt hajóval történjen.</p>
        <p>A tanítás során mindig térjünk ki a szél irányának és a haladási iránynak a viszonyára, valamint a vitorla beállítására is (pl.: hátszél: hátulról fúj a szél, teljesen kiengedem a vitorlát).</p>
        
        <img alt='szélirány' title="szélirány">
        <h3>Csomó fajták</h3>
    <table>
        
        <caption>
            <b>
                Alap csomók
            </b>
            </caption>
        <tr>
            <th>Csomó neve</th>
            <th>Csomó képe</th>
        </tr>
        <tr>
            <td>
                <img src="forrás/ecsomo.JPG" alt="Egyszerű csomó">
            </td>
            <td>Egyszerű csomó</td>
        </tr>
        <tr>
            <td>
                <img src="forrás/tcsomo.JPG" alt="Takács csomó">

            </td>
            <td>Takács csomó</td>
        </tr>
        <tr>
            <td>
                <img src="forrás/pcsomo.JPG" alt="Palstek csomó">

            </td>
            <td>Palstek csomó</td>
        </tr>
        <tr>
            <td>
                <img src="forrás/knyolcas.JPG" alt="Kikötő nyolcas">

            </td>
            <td>Kikötő nyolcas</td>
        </tr>
    </table>    
        Észrevételek
        
        generálj 2 bekezdésnyi szöveget! Formázd a minta szerint!
        
        
        <hr>
        http://www.nupi.hu/download/sportiskola/modszertani/modszertan_vitorlazas.pdf új lapfülön nyíljon meg a böngészőbe
        
        Oldaltérkép: Oldalon belül a főbb témakörök linkjei.
        

    </main>
    <footer>


    </footer>
</body>
</html>